# Generated by Django 4.2.10 on 2024-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_category_options_alter_movie_options_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(related_name='movies', to='movies.comment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(related_name='movies', to='movies.rating'),
        ),
    ]
